# Our Adjusted Golang Image 
FROM golang:latest
LABEL maintainer="bob@2kranki.us"
#RUN apt-get update && apt-get install --yes vim
#COPY ./usr/src/app/* /usr/src/app/
#CMD "/usr/src/app/entrypoint.sh"
